name: papirus
version: 'Latest'
base: core22
summary: Latest Complete Set of Papirus-Icons
description: |
  This snap provides the Papirus Icon Theme in a form that can be used
  by other snapped applications. It can be installed alongside the
  gtk-common-themes snap.
grade: stable
compression: lzo
confinement: strict
architectures:
  - build-on: amd64
    build-for: amd64


slots:
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/usr/share/icons/Papirus-Dark
        - $SNAP/usr/share/icons/Papirus
        - $SNAP/usr/share/icons/Papirus-Light
        - $SNAP/usr/share/icons/ePapirus-Dark
        - $SNAP/usr/share/icons/ePapirus

parts:      
  papirus:
    source: https://github.com/PapirusDevelopmentTeam/papirus-icon-theme.git
    source-depth: 1
    plugin: make
    build-packages:
     - gtk-update-icon-cache
     
    override-prime: |
        craftctl default
        update-icon-caches /usr/share/icons/*
        
   
