name: Build snap

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: snapcore/action-build@v1
      id: build
    - uses: actions/upload-artifact@v3
      with:
        name: my.snap
        path: ${{ steps.build.outputs.snap}}
